package Modelo;

public enum Juegos {

    PAC_MAN, SPACE_INVADERS, DONKEY_KONG, STREET_FIGHTER_II, GALAGA, MORTAL_KOMBAT, ASTEROIDS, FROGGER, 
    TETRIS, CENTIPEDE, DOUBLE_DRAGON, DEFENDER, OUT_RUN, NBA_JAM, METAL_SLUG, TEENAGE_MUTANT_NINJA_TURTLES, 
    X_MEN,  THE_SIMPSONS, TIME_CRISIS
    
}
